version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data